application1:
  deployment:
    name: frontend
    replicaCount: 1
  namespace: app1
  image:
    name: keeper521/frontend
  # Overrides the image tag whose default is the chart appVersion.
    tag: ""
  container:
    resources:
     limits:
       cpu: 200m
       memory: 256Mi
     requests:
       cpu: 100m
       memory: 128Mi
  appPort: 80

application2:
  deployment:
    name: backend
    replicaCount: 1
  namespace: app1
  image:
    name: keeper521/backend
  # Overrides the image tag whose default is the chart appVersion.
    tag: ""
  container:
    resources:
     limits:
       cpu: 200m
       memory: 256Mi
     requests:
       cpu: 100m
       memory: 128Mi
  appPort: 80
  
application3:
  deployment:
    name: postgres
    replicaCount: 1
  namespace: app1
  image:
    name: keeper521/postgres
  # Overrides the image tag whose default is the chart appVersion.
    tag: ""
  container:
    resources:
     limits:
       cpu: 1
       memory: 512Mi
     requests:
       cpu: 500m
       memory: 256Mi
  appPort: 5432
