all:
  hosts:
    cp-1:
      ansible_host: 84.252.143.39
      ansible user: keeper
    node-1:
      ansible_host: 84.252.138.8
      ansible user: keeper
    node-2:
      ansible_host: 84.201.143.241
      ansible user: keeper
    node-3:
      ansible_host: 84.252.138.111
      ansible user: keeper
    node-4:
      ansible_host: 84.252.137.237
      ansible user: keeper
  children:
    kube_control_plane:
      hosts:
        cp-1:
    kube_node:
      hosts:
        node-1:
        node-2:
        node-3:
        node-4:
    etcd:
      hosts:
        cp-1:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}

