apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: test
  name: test
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
        - name: frontend 
          image: keeper521/frontend:latest
          imagePullPolicy: IfNotPresent
          command: ["/bin/sleep", "3650d"]
          ports:
          - containerPort: 8000
        - name: backend
          image: keeper521/backend:latest
          imagePullPolicy: IfNotPresent
          command: ["/bin/sleep", "3650d"]
          ports:
          - containerPort: 9000

---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: default
spec:
  ports:
    - name: frontend
      port: 8000
  selector:
    app: test
    
---
apiVersion: v1    
kind: Service
metadata:
  name: backend
  namespace: default
spec:
  ports:
    - name: backend
      port: 9000
  selector:
    app: test
