apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.application1.deployment.name }}
  labels:
    app: {{ .Values.application1.deployment.name }}
  namespace: {{ .Values.application1.namespace }}
spec:
  replicas: {{ .Values.application1.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.application1.deployment.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.application1.deployment.name }}
    spec:
      containers:
        - name: {{ .Values.application1.deployment.name }}
          image: "{{ .Values.application1.image.name }}:{{ default .Chart.AppVersion }}"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: {{ .Values.application1.appPort }}
              protocol: TCP
          resources:
            {{- toYaml .Values.application1.container.resources | nindent 12 }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.application2.deployment.name }}
  labels:
    app: {{ .Values.application2.deployment.name }}
  namespace: {{ .Values.application2.namespace }}
spec:
  replicas: {{ .Values.application2.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.application2.deployment.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.application2.deployment.name }}
    spec:
      containers:
        - name: {{ .Values.application2.deployment.name }}
          image: "{{ .Values.application2.image.name }}:{{ default .Chart.AppVersion }}"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: {{ .Values.application2.appPort }}
              protocol: TCP
          resources:
            {{- toYaml .Values.application2.container.resources | nindent 12 }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.application3.deployment.name }}
  labels:
    app: {{ .Values.application3.deployment.name }}
  namespace: {{ .Values.application3.namespace }}
spec:
  replicas: {{ .Values.application3.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.application3.deployment.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.application3.deployment.name }}
    spec:
      containers:
        - name: {{ .Values.application3.deployment.name }}
          image: "{{ .Values.application3.image.name }}:{{ default .Chart.AppVersion }}"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: {{ .Values.application3.appPort }}
              protocol: TCP
          resources:
            {{- toYaml .Values.application3.container.resources | nindent 12 }}